### ISSUE TITLE
[Bug] Output generation can't be cancelled

### ISSUE THREAD

**Issue by DifferentialityDevelopment** [juliooa/secondbrain#1]
When giving the model a prompt and it begins outputting a response and you cancel, it does not actually cancel but instead continues outputting.

**Comment by DifferentialityDevelopment** [comment]
Ran the issue through ChatGPT with the relevant source code files and it spat this out.

To properly cancel the inference process, you need to make some changes to your code. Here's what you can do:

1. Add a cancellation flag: Create a mutable flag variable to keep track of the cancellation status. Add it to the state of your application.

   In `llm.ts`:
   ```typescript
   let cancelFlag = false;
   ```

2. Modify the `ask` function: Update the `ask` function to store the cancellation flag and check it during inference. If the flag is set to `true`, stop the inference loop and return an appropriate response.

   In `llm.ts`:
   ```typescript
   export async function ask(message: string): Promise<string> {
     cancelFlag = false; // Reset the cancellation flag
     try {
       const result = await invoke('ask', { message: message });
       return result;
     } catch (error) {
       if (error.message === 'Operation aborted') {
         return 'Inference cancelled.';
       }
       throw error;
     }
   }
   ```

3. Modify the inference loop: Update the `ask` function in the Rust code to check the cancellation flag at each step of the inference loop. If the flag is set to `true`, stop the loop by returning an appropriate `Err` value.

   In `language_model.rs`:
   ```rust
   // Add a new argument to the `ask` function to receive the cancellation status.
   pub async fn ask(
       message: String,
       app_handle: tauri::AppHandle,
       window: tauri::Window,
       cancellation_status: Arc<AtomicBool>,
   ) -> String {
       // ...

       let res = session.infer::<Infallible>(
           model.as_ref(),
           &mut rand::thread_rng(),
           &InferenceRequest {
               // ...
           },
           &mut Default::default(),
           |inference_response| {
               if cancellation_status.load(Ordering::Relaxed) {
                   Err(llm::Error::new("Operation aborted"))
               } else {
                   match inference_response {
                       llm::InferenceResponse::PromptToken(_) => {
                           Ok(llm::InferenceFeedback::Continue)
                       }
                       llm::InferenceResponse::InferredToken(t) => {
                           // ...
                           Ok(llm::InferenceFeedback::Continue)
                       }
                       _ => Ok(llm::InferenceFeedback::Continue),
                   }
               }
           },
       );

       // ...
   }
   ```

4. Implement the cancellation feature: Modify the Svelte component to include a "Cancel" button and handle its click event to set the cancellation flag.

   In `qa/page.svelte`:
   ```html
   <script lang="ts">
     // ...

     async function cancel_inference() {
       cancelFlag = true; // Set the cancellation flag
       // ...
     }
   </script>

   <!-- Inside the form -->
   <button
     type="button"
     class="btn variant-filled-error w-1/5 ml-4 text-xl"
     on:click={() => {
       cancel_inference();
     }}
     disabled={!loading}
   >
     Cancel
   </button>
   ```

By introducing the cancellation flag and checking it during the inference loop, you can effectively stop the inference process when the cancellation is requested.

**Comment by juliooa** [comment]
Hi man, thanks for the code! I was super busy the last two weeks, now I will start tackling the issues.

Chatgpt it's kind of outdated with Svelte, there were many changes after its cut-off date. But feel free to send PRs if you want, we can go through it.

**Comment by juliooa** [comment]
Last release fixes this: https://github.com/juliooa/secondbrain/releases/tag/v0.2.1
